name: Call API every minute

on:
  schedule:
    - cron: '* * * * *'

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call API endpoint
        run: curl -X GET https://monex-eight.vercel.app/api/tasas
